routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
  

/* Borrower Routes */
Route::name('admin.')->middleware(['auth','role:admin'])->group(function () {
        Route::get('', [DashboardController::class, 'index'])->name('home');

  
        Route::group(['prefix' => 'users', 'as' => 'users.'], function(){
                Route::controller(UserController::class)->group(function () {
                        Route::get('', 'index')->name('index');
                        Route::get('subordinate-pending', 'pending')->name('subordinate.pending');
                        Route::get('vip-requests', 'listVipRequest')->name('vip.requests');
                        Route::get('superior', 'superior')->name('superior');
                        Route::get('list-superior', 'listSup')->name('list.superior');
                        Route::get('list-subordinate', 'listSub')->name('list.subordinate');
                        Route::get('list-subordinate-pending', 'listSubPending')->name('list.subordinate.pending');
                        Route::post('save/{id?}', 'save')->name('save');
                        Route::post('approve-account/{id?}', 'approveAccount')->name('account.approve');
                        Route::get('find/{id?}', 'find')->name('find');
                        Route::delete('delete/{id?}', 'delete')->name('delete');
                });
        });


});


?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('website');

Route::get('/contact-us', function () {
    return view('contact_us');
})->name('contact_us');

Route::get('/login', function () {
    return view('login');
})->name('login');



/*Registration form*/
Route::get('register/{invite_id?}', [AuthController::class, 'register'])->name('join');

Route::group(['prefix' => 'auth', 'as' => 'auth.'], function(){
    Route::controller(AuthController::class)->group(function () {
        Route::post('create-account', 'createAccount')->name('register');
        Route::post('login-account', 'loginAccount')->name('login');
        Route::get('logout-account', 'logout')->name('logout');
        Route::get('new-captcha', 'renewCaptcha')->name('new.captcha');
        Route::get('verify-account/{token?}', 'verifyAccount')->name('verify');
    });
});

Route::group(['prefix' => 'users', 'as' => 'users.'], function(){
    Route::controller(UserController::class)->group(function () {
        Route::get('', 'index')->name('index');
        Route::get('list', 'list')->name('list');
        Route::post('save/{id?}', 'save')->name('save');
        Route::get('find/{id?}', 'find')->name('find');
        Route::delete('delete/{id?}', 'delete')->name('delete');
    });
});

resources/views/join_now.blade.php
<?php 
    $link = "http://proxy.abcfishinggames.com:8180/apk_proxy/apk/download.html?accountId=3160397";
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <title>Registration</title>

    <link rel="shortcut icon" href="images/fav.png" type="image/x-icon">
    <link rel="stylesheet" href="{{ asset('website/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/fontawesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/slick.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/magnific-popup.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/nice-select.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/animate.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('css/sweetalert.css') }}">

</head>

<body>

    <!-- start preloader -->
    <div class="preloader" id="preloader"></div>
    <!-- end preloader -->

    <a href="#" class="scrollToTop"><i class="fas fa-angle-double-up"></i></a>

    <!-- header-section start -->
     <header id="header-section">
        <div class="overlay">
            <div class="container">
                <div class="row d-flex align-items-center">
                    <div class="logo-section flex-grow-1 d-flex align-items-center">
                        <a class="site-logo site-title" href="{{ route('website') }}?#banner-section"><img src="{{ asset('logo.png') }}" width="65" 
                                alt="site-logo"></a>
                    </div>
                    <button class="navbar-toggler ml-auto collapsed" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-bars"></i>
                    </button>
                    <nav class="navbar navbar-expand-lg p-0">
                        <div class="navbar-collapse collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav main-menu ml-auto">
                                <li><a href="{{ route('website') }}?#banner-section">Home</a></li>
                                <li><a href="{{ route('website') }}?#how-works-section">How to Join?</a></li>
                                <li><a href="{{ route('website') }}?#features-section">Features</a></li>
                                <li><a href="#" onclick="modal_disclaimer();">Disclaimer</a></li>
                                <li><a href="{{ route('contact_us') }}">Contact Us</a></li>
                            </ul>
                        </div>
                    </nav>
                      <div class="right-area header-action d-flex align-items-center">
                        <a href="{{ route('login') }}" class="cmn-btn">Login</a>
                        <a href="{{ route('join') }}" class="cmn-btn">Sign Up</a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-section end -->

    <!-- Contact Start -->
    <section id="contact-section">
        <div class="overlay">
            <div class="container">
                <div class="row justify-content-center pt-120 pb-120" style="margin-top: 110px;">
                    <div class="col-md-6">
                        <h3>Instructions.</h3>
                        <p>Please follow all the Instructions first before register your account.</p>
                        
                        <p class="mt-3">1. Download and Install the APP.</p>
                        <div class="row">
                            <div class="col-md-12">
                                <a href="javascript:;" onclick="window.open('{{ $link }}','_blank','width=600,height=1000,top=0,left=1500')" class="cmn-btn text-white" type="submit"><img src="{{ asset('website/images/android.png') }}" width="20"> Download</a>
                                <a href="javascript:;" onclick="window.open('{{ $link }}','_blank','width=600,height=1000,top=0,left=1500')" class="cmn-btn text-white" type="submit"><img src="{{ asset('website/images/ios.png') }}" width="20"> Download</a>

                            </div>
                        </div>
                        <p class="mt-3">2. Login via Facebook Or Mobile.</p>
                        <a href="{{ asset('info/1.png') }}" target="_blank"><img src="{{ asset('info/1.png') }}" alt="" class="img-fluid"></a>
                        <p class="mt-3">3. On the homepage click this menu.</p>
                        <a href="{{ asset('info/2.png') }}" target="_blank"><img src="{{ asset('info/2.png') }}" alt="" class="img-fluid"></a>
                        <p class="mt-3">3. Get your <b>LELE GOLD Account ID</b> use this for your registraion.</p>
                        <p class="mt-3">NOTE: Make sure that your superior ID is <b>3160397</b>.</p>
                        <a href="{{ asset('info/3.png') }}" target="_blank"><img src="{{ asset('info/3.png') }}" alt="" class="img-fluid"></a>
                        <p class="mt-3">4. Use your Email address and <b>LELE GOLD Account ID</b> to register.</p>
                        <a href="{{ asset('info/5.png') }}" target="_blank" class="mb-5"><img src="{{ asset('info/5.png') }}" alt="" class="img-fluid"></a>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5 ">
                        <form id="user_form" class="needs-validation" action="{{ route('auth.register') }}" method="post">
                            <h5>Register Your Account Here.</h5>
                             <input type="hidden" name="g-token" id="g-token">
                            <input type="hidden" style="opacity: 0;" name="ref_id" id="ref_id" value="{{ $invite_code }}">
                            <div class="form-group">
                                <label for="email_address">Name</label>
                                <input type="text" id="name" name="name" placeholder="Enter your Name" class="form-control text-capitalize">
                            </div>
                            <div class="form-group">
                                <label for="email_address">Email Address</label>
                                <input type="text" id="email_address" name="email_address" placeholder="Enter your Name" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="lele_id">Lele Gold ID</label>
                                <input type="text" id="lele_id" name="lele_id" maxlength="10" placeholder="Enter Lele Gold Account ID" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="confirm_lele_id">Confirm ID</label>
                                <input type="text" id="confirm_lele_id" maxlength="10" name="confirm_lele_id" placeholder="Confirm Lele Gold Account ID" class="form-control">
                            </div>
                            <div class="text-right">
                                <button class="cmn-btn" id="submit" type="submit">Register</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact End -->

    @include('modal_disclaimer')
    <script src="{{ asset('website/js/jquery-3.5.1.min.js') }}"></script>
    <script src="{{ asset('website/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('website/js/slick.js') }}"></script>
    <script src="{{ asset('website/js/jquery.nice-select.min.js') }}"></script>
    <script src="{{ asset('website/js/fontawesome.js') }}"></script>
    <script src="{{ asset('website/js/jquery.counterup.min.js') }}"></script>
    <script src="{{ asset('website/js/jquery.waypoints.min.js') }}"></script>
    <script src="{{ asset('website/js/jquery.magnific-popup.min.js') }}"></script>
    <script src="{{ asset('website/js/wow.js') }}"></script>
    <script src="{{ asset('website/js/main.js') }}"></script>
    <script src="{{ asset('js/csrf-ajax.js') }}"></script>
    <script src="{{ asset('js/sweetalert.min.js') }}"></script>
    <script src="{{ asset('js/validation.js') }}"></script>
    <script src="https://www.google.com/recaptcha/api.js?render=6LfHJvkjAAAAABZdHFU_9n-YdGn2u8uwGsFSqZfY"></script>
    @include('script_disclaimer')

    <script type="text/javascript">
        get_new_recapcha();

        // Token from capthca
        function get_new_recapcha(){
         grecaptcha.ready(function() {
              grecaptcha.execute('6LfHJvkjAAAAABZdHFU_9n-YdGn2u8uwGsFSqZfY', {action: 'contact_form'}).then(function(token) {
                  $("#g-token").val(token);
              });
            });
        }

        $("#user_form").on('submit', function(e){
            e.preventDefault();
            let url = $(this).attr('action');
            let formData = $(this).serialize();
            $.ajax({
                type:"POST",
                url:url,
                data:formData,
                dataType:'json',
                beforeSend:function(){
                    $('#submit').prop('disabled', true);
                    $('#submit').text('Please Wait...');
                },
                success:function(response){
                    // console.log(response);
                    if (response.status == true) {
                        swal("Thank you!", response.message, "success");
                        get_new_recapcha();
                        $("#name").val('');
                        $("#email_address").val('');
                        $("#lele_id").val('');
                        $("#confirm_lele_id").val('');
                    }else{
                        swal("Error", response.message, "error");
                        get_new_recapcha();
                    }
                        validation('user_form', response.error);
                        $('#user_form_btn').prop('disabled', false);
                    $('#submit').prop('disabled', false);
                    $('#submit').text('Register');

                },
                error: function(error){
                    $('#submit').prop('disabled', false); 
                    $('#submit').text('Register');                   
                    swal("Error", "Please try again later.", "error");
                }
            });
        });

    </script>
</body>

</html>

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <link rel="shortcut icon" href="images/fav.png" type="image/x-icon">
    <link rel="stylesheet" href="{{ asset('website/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/fontawesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/slick.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/magnific-popup.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/nice-select.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/animate.css') }}">
    <link rel="stylesheet" href="{{ asset('website/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('css/sweetalert.css') }}">

</head>

<body>

    <!-- start preloader -->
    <div class="preloader" id="preloader"></div>
    <!-- end preloader -->

    <a href="#" class="scrollToTop"><i class="fas fa-angle-double-up"></i></a>

    <!-- header-section start -->
     <header id="header-section">
        <div class="overlay">
            <div class="container">
                <div class="row d-flex align-items-center">
                    <div class="logo-section flex-grow-1 d-flex align-items-center">
                        <a class="site-logo site-title" href="{{ route('website') }}?#banner-section"><img src="{{ asset('logo.png') }}" width="65" 
                                alt="site-logo"></a>
                    </div>
                    <button class="navbar-toggler ml-auto collapsed" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-bars"></i>
                    </button>
                    <nav class="navbar navbar-expand-lg p-0">
                        <div class="navbar-collapse collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav main-menu ml-auto">
                                <li><a href="{{ route('website') }}?#banner-section">Home</a></li>
                                <li><a href="{{ route('website') }}?#how-works-section">How to Join?</a></li>
                                <li><a href="{{ route('website') }}?#features-section">Features</a></li>
                                <li><a href="#" onclick="modal_disclaimer();">Disclaimer</a></li>
                                <li><a href="{{ route('contact_us') }}">Contact Us</a></li>
                            </ul>
                        </div>
                    </nav>
                      <div class="right-area header-action d-flex align-items-center">
                        <a href="{{ route('login') }}" class="cmn-btn">Login</a>
                        <a href="{{ route('join') }}" class="cmn-btn">Sign Up</a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-section end -->

    <!-- Contact Start -->
    <section id="contact-section" class="pt-120 pb-120" style="margin-top: 120px;">
        <div class="overlay">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <form id="login_form" action="{{ route('auth.login') }}" class="needs-validation" method="post">
                            <h5>Login your account.</h5>
                             <input type="hidden" name="g-token" id="g-token">
                            <div class="form-group">
                                <label for="contact_number">Email Address</label>
                                <input type="email" id="email_address" name="email_address" class="form-control" placeholder="Enter your Email Address">
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" id="password" name="password" class="form-control" placeholder="Enter your email">
                            </div>
                            <div class="text-right">
                                <button class="cmn-btn" type="button" onclick="window.location ='{{ route('join') }}'">Sign Up</button>
                                <button class="cmn-btn" type="submit" id="submit">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact End -->

    @include('modal_disclaimer')



    <script src="{{ asset('website/js/jquery-3.5.1.min.js') }}"></script>
    <script src="{{ asset('website/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('website/js/slick.js') }}"></script>
    <script src="{{ asset('website/js/jquery.nice-select.min.js') }}"></script>
    <script src="{{ asset('website/js/fontawesome.js') }}"></script>
    <script src="{{ asset('website/js/jquery.counterup.min.js') }}"></script>
    <script src="{{ asset('website/js/jquery.waypoints.min.js') }}"></script>
    <script src="{{ asset('website/js/jquery.magnific-popup.min.js') }}"></script>
    <script src="{{ asset('website/js/wow.js') }}"></script>
    <script src="{{ asset('website/js/main.js') }}"></script>
    <script src="{{ asset('js/csrf-ajax.js') }}"></script>
    <script src="{{ asset('js/sweetalert.min.js') }}"></script>
    <script src="{{ asset('js/validation.js') }}"></script>
    <script src="https://www.google.com/recaptcha/api.js?render=6LfHJvkjAAAAABZdHFU_9n-YdGn2u8uwGsFSqZfY"></script>

    @include('script_disclaimer')

    <script type="text/javascript">
         get_new_recapcha();

        // Token from capthca
        function get_new_recapcha(){
         grecaptcha.ready(function() {
              grecaptcha.execute('6LfHJvkjAAAAABZdHFU_9n-YdGn2u8uwGsFSqZfY', {action: 'contact_form'}).then(function(token) {
                  $("#g-token").val(token);
              });
            });
        }
        $("#login_form").on('submit', function(e){
            e.preventDefault();
            let url = $(this).attr('action');
            let formData = $(this).serialize();
            $.ajax({
                type:"POST",
                url:url,
                data:formData,
                dataType:'json',
                beforeSend:function(){
                    $('#submit').prop('disabled', true);
                    $('#submit').text('Please Wait...');
                },
                success:function(response){
                    // console.log(response);
                    if (response.status == true) {
                        // console.log(response);    
                        window.location= response.redirect;                    
                    }else{
                        swal("Error", response.message, "error");
                        get_new_recapcha();
                        console.log(response);
                    }
                        validation('login_form', response.error);
                        $('#login_form_btn').prop('disabled', false);
                    $('#submit').prop('disabled', false);
                    $('#submit').text('Login');

                },
                error: function(error){
                    $('#submit').prop('disabled', false); 
                    $('#submit').text('Login');                   
                    console.log(error);
                }
            });
        });
    </script>

</body>

</html>

resources/views/modal_disclaimer.blade.php
 <div class="modal fade" role="dialog" id="age_modal" style="background: transparent; backdrop-filter: blur(10px);">
      <div class="modal-dialog">
        <div class="modal-content" style="background: #201678 !important;">                
          <div class="modal-body text-center">
             <h5 class="mt-4">Are you age 20 or above?</h5>
             <br>
              <div class="btn-play d-flex justify-content-center align-items-center text-center">
                <a href="#javascript:;" onclick="window.location = 'https://www.youtube.com/watch?v=e_04ZrNroTo'" class="cmn-btn mr-3">No</a>
                <a href="#javascript:;" onclick="modal_disclaimer();" class="cmn-btn">Yes, I am</a>
            </div>
          </div>
        </div>
      </div>
    </div>
<!-- footer-section end -->
 <div class="modal fade" role="dialog" id="modal_disclaimer" style="background: transparent; backdrop-filter: blur(10px);">
      <div class="modal-dialog">
        <div class="modal-content" style="background: #201678 !important;">
          <div class="modal-header" style="border:none!important;">
            <div class="modal-title">
            <h3>Disclaimer</h3>
            </div>
          </div>
          <div class="modal-body">
            <h4>Lele Gold</h4>
            <p>is a play to earn games.</p>
            <br>
            <p>We are not forcing anyone to invest or download this game. You can play and earn with this game without investing.</p>
            <br>
            <h4><b style="color:red;">Do your own Research</b></h4>
            <p>Please research before investing and put some money into this game.</p>
            <br>
            <h4><b style="color:red;">Take your own risk</b></h4>
            <p>The game is meant to play and to have fun. And if you spend or put some money into this do it at your own risk.</p>
            <br><br>
            <div class="btn-play d-flex justify-content-center align-items-center text-center">
                <a href="#javascript:;" data-dismiss="modal" onclick="underestand();" class="cmn-btn" style="height: 80px !important; width:300px; padding: 20px; font-size:30px;">I Understand</a>
            </div>
          </div>
        </div>
      </div>
    </div>

resources/views/script_disclaimer.blade.php
 <script type="text/javascript">
        function underestand(){
             localStorage.setItem("agreement","yes");
             $('html, body').css({
                overflow: 'auto',
                height: 'auto'
            });
        }

       
        //getting localStorage.
        function modal_age(){
            $("#age_modal").modal({'backdrop': 'static'});
            $('html, body').css({
                overflow: 'hidden',
                height: '100%'
            });
        }

        function modal_disclaimer(){
            $("#age_modal").modal('hide');
            $("#modal_disclaimer").modal({'backdrop': 'static'});
            $('html, body').css({
                overflow: 'hidden',
                height: '100%'
            });
        }

        const agreement = localStorage.getItem('agreement');
        console.log(agreement);
        if(agreement == 'yes'){

        }else{
            modal_age();            
        }


        $("html body").on('click', function(){
            var audio = new Audio("{{ asset('type.wav') }}");

          audio.play();
        });


    </script>