routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
  

/* Borrower Routes */
Route::name('admin.')->middleware(['auth','role:admin'])->group(function () {
        Route::get('', [DashboardController::class, 'index'])->name('home');

  
        Route::group(['prefix' => 'users', 'as' => 'users.'], function(){
                Route::controller(UserController::class)->group(function () {
                        Route::get('', 'index')->name('index');
                        Route::get('subordinate-pending', 'pending')->name('subordinate.pending');
                        Route::get('vip-requests', 'listVipRequest')->name('vip.requests');
                        Route::get('superior', 'superior')->name('superior');
                        Route::get('list-superior', 'listSup')->name('list.superior');
                        Route::get('list-subordinate', 'listSub')->name('list.subordinate');
                        Route::get('list-subordinate-pending', 'listSubPending')->name('list.subordinate.pending');
                        Route::post('save/{id?}', 'save')->name('save');
                        Route::post('approve-account/{id?}', 'approveAccount')->name('account.approve');
                        Route::get('find/{id?}', 'find')->name('find');
                        Route::delete('delete/{id?}', 'delete')->name('delete');
                });
        });


});


?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('website');

Route::get('/contact-us', function () {
    return view('contact_us');
})->name('contact_us');

Route::get('/login', function () {
    return view('login');
})->name('login');



/*Registration form*/
Route::get('register/{invite_id?}', [AuthController::class, 'register'])->name('join');

Route::group(['prefix' => 'auth', 'as' => 'auth.'], function(){
    Route::controller(AuthController::class)->group(function () {
        Route::post('create-account', 'createAccount')->name('register');
        Route::post('login-account', 'loginAccount')->name('login');
        Route::get('logout-account', 'logout')->name('logout');
        Route::get('new-captcha', 'renewCaptcha')->name('new.captcha');
        Route::get('verify-account/{token?}', 'verifyAccount')->name('verify');
    });
});

Route::group(['prefix' => 'users', 'as' => 'users.'], function(){
    Route::controller(UserController::class)->group(function () {
        Route::get('', 'index')->name('index');
        Route::get('list', 'list')->name('list');
        Route::post('save/{id?}', 'save')->name('save');
        Route::get('find/{id?}', 'find')->name('find');
        Route::delete('delete/{id?}', 'delete')->name('delete');
    });
});

resources/views/admin/layout/app.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <title> @yield('title')</title>
    <link rel="icon" type="image/x-icon" href="{{ asset('logo.png') }}">

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">

    <!-- Datatables -->
    <link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables-new/datatables.min.css') }}"/>

    <!-- Lada Button -->
    <link type="text/css" href="{{ asset('plugins/ladda/ladda-themeless.min.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
  
    <link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">

    <link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">

    <!-- Custom style -->
    <link rel="stylesheet" href="{{ asset('style.css') }}">

    <link rel="stylesheet" href="{{ asset('css/sweetalert.css') }}">



    <!-- END PAGE LEVEL PLUGINS/CUSTOM STYLES -->

    @stack('styles')    

    <!-- CUSTOM CSS FILES HERE -->

</head>
    
<body class="hold-transition sidebar-mini sidebar-collapse">

<div class="wrapper">

    @include('admin.layout.navbar')

    @include('admin.layout.sidebar')


    <!-- Content Wrapper. Contains page content -->

      <div class="content-wrapper">

        @include('admin.layout.breadcrumb')

        @yield('content')

      </div>

    <!-- /.content-wrapper -->

    @include('admin.layout.footer')

</div>

<!-- Global Modals -->

@stack('page-modals')

<!-- End Global Modals -->

<!-- BEGIN GLOBAL MANDATORY SCRIPTS -->

<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>

<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- ladda -->
<script src="{{ asset('plugins/ladda/spin.min.js') }}"></script>
<script src="{{ asset('plugins/ladda/ladda.min.js') }}"></script>
<script src="{{ asset('plugins/ladda/ladda.jquery.min.js') }}"></script>

<script src="{{ asset('plugins/sweetalert2/sweetalert2.min.js') }}"></script>

<script src="{{ asset('plugins/datatables-new/datatables.min.js') }}"></script>

<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>

<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>

<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>

<script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
<script src="{{ asset('js/csrf-ajax.js') }}"></script>

<script src="{{ asset('js/sweetalert.min.js') }}"></script>
<script src="{{ asset('js/validation.js') }}"></script>
<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->

@stack('js-scripts') 



</body>
</html>

resources/views/admin/layout/breadcrumb.blade.php
<section class="content-header breadcrumb">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6">
          <h1 class="m-0">{{ View::getSection('title') }}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
            <li class="breadcrumb-item active">{{ View::getSection('title') }}</li>
          </ol>
        </div>
      </div>
    </div>
</section>

resources/views/admin/layout/footer.blade.php
  <!-- <aside class="control-sidebar control-sidebar-dark">
    
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside> -->

<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Version 1.0
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; {{ date('Y') }} <a href="#">Team Bulitas</a>.</strong> All rights reserved.
</footer>

resources/views/admin/layout/navbar.blade.php
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav mr-auto">


    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

      

      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      

      <li class="nav-item">
        <a href="{{ route('auth.logout') }}" class="nav-link">Logout</a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/admin/layout/sidebar.blade.php
 <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-light-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('admin.home') }}" class="brand-link">
      <img src="{{ asset('logo.png') }}" alt="Company Logo" class="brand-image">
      <span class="brand-text font-weight-bold">Lele Gold</span>
    </a>

    <style>
      #avatar_sidebar{
               width: 2rem;
               height: 2rem;
             }
    </style>
    
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
              <img src="{{ asset('dist/img/avatar_default.png') }}" class="img-circle elevation-2" alt="Employee Male Default">
          
        </div>
        <div class="info">
          <a href="" class="d-block"><b>#{{ auth()->user()->lele_id }}</b>{{ auth()->user()->getFullName()  }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item">
              <a href="{{ route('admin.home') }}" class="nav-link {{ (request()->is('admin'))? 'active': '' }}">
                <i class="fas fa-chart-bar"></i>
                <p>Dashboard</p>
              </a>
            </li> 
        </ul>

        @if(auth()->user()->user_type === 1)
         <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item">
              <a href="{{ route('admin.users.superior') }}" class="nav-link {{ (request()->is('admin/users/superior'))? 'active': '' }}">
                <i class="fas fa-user-secret"></i>
                <p>Superior</p>
              </a>
            </li> 
        </ul>
        @endif
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item">
              <a href="{{ route('admin.users.index') }}" class="nav-link {{ (request()->is('admin/users'))? 'active': '' }}">
                <i class="fas fa-users"></i>
                <p>Subordinate</p>
              </a>
            </li> 
        </ul>

        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item">
              <a href="{{ route('admin.users.subordinate.pending') }}" class="nav-link {{ (request()->is('admin/users/subordinate-pending'))? 'active': '' }}">
                <i class="fas fa-user-lock"></i>
                <p>Pending Subordinate</p>
                <span class="badge badge-danger navbar-badge">3</span>
              </a>
            </li> 
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>